--[[
      Using on radio #664
--]]



print("Radio started!")
rednet.open("front")

while true do

print("Still alive started...")
rednet.broadcast("Statilite radio, broadcasting here:")
sleep(3)
rednet.broadcast("Still alive from the game Portal...")
sleep(3)
rednet.broadcast("This was a triumph.")
sleep(3)
rednet.broadcast("Im making a note here: HUGE SUCCESS.")
sleep(3)
rednet.broadcast("Its hard to overstate my satisfaction.")
sleep(3)
rednet.broadcast("Aperture Science")
sleep(3)
rednet.broadcast("We do what we must")
sleep(3)
rednet.broadcast("because we can.")
sleep(3)
rednet.broadcast("For the good of all of us.")
sleep(3)
rednet.broadcast("Except the ones who are dead.")
sleep(3)
rednet.broadcast("But theres no sense crying over every mistake.")
sleep(3)
rednet.broadcast("You just keep on trying till you run out of cake.")
sleep(3)
rednet.broadcast("And the Science gets done.")
sleep(3)
rednet.broadcast("And you make a neat gun.")
sleep(3)
rednet.broadcast("For the people who are still alive.")
sleep(3)
rednet.broadcast("Im not even angry.")
sleep(3)
rednet.broadcast("Im being so sincere right now.")
sleep(3)
rednet.broadcast("Even though you broke my heart.")
sleep(3)
rednet.broadcast("And killed me.")
sleep(3)
rednet.broadcast("And tore me to pieces.")
sleep(3)
rednet.broadcast("And threw every piece into a fire.")
sleep(3)
rednet.broadcast("As they burned it hurt because I was so happy for you!")
sleep(3)
rednet.broadcast("Now these points of data make a beautiful line.")
sleep(3)
rednet.broadcast("And were out of beta.")
sleep(3)
rednet.broadcast("Were releasing on time.")
sleep(3)
rednet.broadcast("So Im GLaD. I got burned.")
sleep(3)
rednet.broadcast("Think of all the things we learned")
sleep(3)
rednet.broadcast("for the people who are still alive.")
sleep(3)
rednet.broadcast("Go ahead and leave me.")
sleep(3)
rednet.broadcast("I think I prefer to stay inside.")
sleep(3)
rednet.broadcast("Maybe youll find someone else to help you.")
sleep(3)
rednet.broadcast("Maybe Black Mesa...")
sleep(3)
rednet.broadcast("THAT WAS A JOKE.")
sleep(3)
rednet.broadcast("HAHA. FAT CHANCE.")
sleep(3)
rednet.broadcast("Anyway, this cake is great.")
sleep(3)
rednet.broadcast("Its so delicious and moist.")
sleep(3)
rednet.broadcast("Look at me still talking")
sleep(3)
rednet.broadcast("when theres Science to do.")
sleep(3)
rednet.broadcast("When I look out there, it makes me GLaD Im not you.")
sleep(3)
rednet.broadcast("Ive experiments to run.")
sleep(3)
rednet.broadcast("There is research to be done.")
sleep(3)
rednet.broadcast("On the people who are still alive.")
sleep(3)
rednet.broadcast("And believe me I am still alive.")
sleep(3)
rednet.broadcast("Im doing Science and Im still alive.")
sleep(3)
rednet.broadcast("I feel FANTASTIC and Im still alive.")
sleep(3)
rednet.broadcast("While youre dying Ill be still alive.")
sleep(3)
rednet.broadcast("And when youre dead I will be still alive.")
sleep(3)
rednet.broadcast("Still alive... still alive.....")
sleep(3)
rednet.broadcast("Next song planned in 5 minutes.")
print("Still alive done, Want you gone is next.")
print("5 min")
sleep(60)
print("4 min")
sleep(60)
print("3 min")
sleep(60)
print("2 min")
sleep(60)
print("1 min")
sleep(60)






print("Want you gone started...")
rednet.broadcast("Statilite radio, broadcasting here:")
sleep(3)
rednet.broadcast("Want you gone from the game Portal 2...")
sleep(3)
rednet.broadcast("Well here we are again,")
sleep(3)
rednet.broadcast("Its always such a pleasure,")
sleep(3)
rednet.broadcast("Remember when you tried to kill me twice?")
sleep(3)
rednet.broadcast("Oh, how we laughed and laughed,")
sleep(3)
rednet.broadcast("Except I wasnt laughing,")
sleep(3)
rednet.broadcast("Under the circumstances Ive been shockingly nice.")
sleep(3)
rednet.broadcast("You want your freedom take it,")
sleep(3)
rednet.broadcast("Thats what Im counting on,")
sleep(3)
rednet.broadcast("I used to want you dead but,")
sleep(3)
rednet.broadcast("Now I only want you gone.")
sleep(3)
rednet.broadcast("She was a lot like you,")
sleep(3)
rednet.broadcast("(Maybe not quite as heavy),")
sleep(3)
rednet.broadcast("Now little Caroline is in here too.")
sleep(3)
rednet.broadcast("One day they woke me up,")
sleep(3)
rednet.broadcast("So I could live forever,")
sleep(3)
rednet.broadcast("Its such a shame the same will never happen to you.")
sleep(3)
rednet.broadcast("Youve got your short, sad life left,")
sleep(3)
rednet.broadcast("Thats what Im counting on,")
sleep(3)
rednet.broadcast("Ill let you get right to it,")
sleep(3)
rednet.broadcast("Now I only want you gone.")
sleep(3)
rednet.broadcast("Goodbye, my only friend,")
sleep(3)
rednet.broadcast("Oh, did you think I meant you?")
sleep(3)
rednet.broadcast("That would be funny if it werent so sad,")
sleep(3)
rednet.broadcast("Well you have been replaced,")
sleep(3)
rednet.broadcast("I dont need anyone now,")
sleep(3)
rednet.broadcast("When I delete you maybe Ill stop feeling so bad.")
sleep(3)
rednet.broadcast("Go make some new disaster,")
sleep(3)
rednet.broadcast("Thats what Im counting on,")
sleep(3)
rednet.broadcast("Youre someone elses problem,")
sleep(3)
rednet.broadcast("Now I only want you gone,")
sleep(3)
rednet.broadcast("Now I only want you gone,")
sleep(3)
rednet.broadcast("Now I only want you gone.")
sleep(3)
rednet.broadcast("Next song planned in 5 minutes.")
print("Want you gone, On the other side of the radio is next.")
print("5 min")
sleep(60)
print("4 min")
sleep(60)
print("3 min")
sleep(60)
print("2 min")
sleep(60)
print("1 min")
sleep(60)





print("On the other side of the radio started...")
rednet.broadcast("Statilite radio, broadcasting here:")
sleep(3)
rednet.broadcast("On the other side of the radio...")
sleep(3)
rednet.broadcast("By: Chris Rice")
sleep(3)
rednet.broadcast("Here I am on the other side of the radio")
sleep(3)
rednet.broadcast("Wonderin why Im here and why anybody cares what I say")
sleep(3)
rednet.broadcast("No Im not a better man cause Im singing my songs on the radio")
sleep(3)
rednet.broadcast("Cause were all the same, at the end of the day")
sleep(3)
rednet.broadcast("Now I imagine you on the other side of the radio")
sleep(3)
rednet.broadcast("Doin your homework or driving with your windows down on the freeway")
sleep(3)
rednet.broadcast("I see you tappin the wheel I see you bobbin your head to the radio")
sleep(3)
rednet.broadcast("Oh and it makes my day, to see that smile on your face")
sleep(3)
rednet.broadcast("And in some small way, I remember my place")
sleep(3)
rednet.broadcast("Cause its you and me singing the same song right now")
sleep(3)
rednet.broadcast("And maybe this will bring us together somehow")
sleep(3)
rednet.broadcast("And maybe theres a million people all singing a long")
sleep(3)
rednet.broadcast("Somebody started thinkin about the third line")
sleep(3)
rednet.broadcast("And maybe someones saying a prayer for the first time")
sleep(3)
rednet.broadcast("And thats enough reason to keep me singing my song,")
sleep(3)
rednet.broadcast("Singing my songs, on the other side of the radio")
sleep(3)
rednet.broadcast("Crank up the volume sing at the top of your lungs with the radio")
sleep(3)
rednet.broadcast("Tune it in to some good news and laughing along with the DJ")
sleep(3)
rednet.broadcast("Were changing someones world from the other side of the radio")
sleep(3)
rednet.broadcast("Oh and it makes my day to see that smile on your face")
sleep(3)
rednet.broadcast("And in some small way, I remember my place")
sleep(3)
rednet.broadcast("Cause its you and me singing the same song right now")
sleep(3)
rednet.broadcast("And maybe this will bring us together somehow")
sleep(3)
rednet.broadcast("And maybe theres a million people all singing a long")
sleep(3)
rednet.broadcast("Somebody started thinkin about the third line")
sleep(3)
rednet.broadcast("And maybe someones saying a prayer for the first time")
sleep(3)
rednet.broadcast("And thats enough reason to keep me singing my song")
sleep(3)
rednet.broadcast("Singing my song, on the other side of the radio")
sleep(3)
rednet.broadcast("Other side of the radio. Dah Dah dah dah dah dah dah dah")
sleep(3)
rednet.broadcast("Other Side of the Radio, other Side of the Radio, ther Side of the Radio")
sleep(3)
rednet.broadcast("Next song planned in 5 minutes.")
print("On the other side of the radio done, TNT is next.")
print("5 min")
sleep(60)
print("4 min")
sleep(60)
print("3 min")
sleep(60)
print("2 min")
sleep(60)
print("1 min")
sleep(60)



print("Now playing Tnt...")
rednet.broadcast("Statilite radio, broadcasting here:")
sleep(3)
rednet.broadcast("TnT by Captn Sparkles.")
sleep(3)
rednet.broadcast("I came to dig dig dig dig")
sleep(3)
rednet.broadcast("Ill build a city oh so big big big big")
sleep(3)
rednet.broadcast("Just wait a sec, gotta kill this pig pig pig pig")
sleep(3)
rednet.broadcast("Cook me some bacon take a swig swig swig swig")
sleep(3)
rednet.broadcast("Yeah, yeah")
sleep(3)
rednet.broadcast("There must be something I can craft")
sleep(3)
rednet.broadcast("To ease the burden of this task")
sleep(3)
rednet.broadcast("Yeah")
sleep(3)
rednet.broadcast("I shoot my arrows in the air sometimes")
sleep(3)
rednet.broadcast("Sayin ay-oh, Creepers K-Od")
sleep(3)
rednet.broadcast("Loot his remains and now his sulphurs mine")
sleep(3)
rednet.broadcast("Saying ay-oh, not today no")
sleep(3)
rednet.broadcast("And then Ill go to work")
sleep(3)
rednet.broadcast("Under the birch tree")
sleep(3)
rednet.broadcast("And Ill make myself")
sleep(3)
rednet.broadcast("Tons of TNT")
sleep(3)
rednet.broadcast("and Ill use these blocks")
sleep(3)
rednet.broadcast("To build a big city")
sleep(3)
rednet.broadcast("And Ill mine it all")
sleep(3)
rednet.broadcast("Using TNT")
sleep(3)
rednet.broadcast("I came to blow blow blow blow")
sleep(3)
rednet.broadcast("Up everything youve ever known known known known")
sleep(3)
rednet.broadcast("Expel you out of house and home home home home")
sleep(3)
rednet.broadcast("Biome to biome you shall roam roam roam roam")
sleep(3)
rednet.broadcast("Yeah, yeah")
sleep(3)
rednet.broadcast("cause Im a creeper I will rob")
sleep(3)
rednet.broadcast("All of your items thats my job")
sleep(3)
rednet.broadcast("Yeah")
sleep(3)
rednet.broadcast("I shoot my arrows in the air sometimes")
sleep(3)
rednet.broadcast("Sayin ay-oh, Creepers K-Od")
sleep(3)
rednet.broadcast("Teabag his ghost and now his sulphurs mine")
sleep(3)
rednet.broadcast("Sayin ay-oh, MLG pro")
sleep(3)
rednet.broadcast("And then Ill head back home")
sleep(3)
rednet.broadcast("Where Ill smile with glee")
sleep(3)
rednet.broadcast("Now that I can make")
sleep(3)
rednet.broadcast("tons of TNT")
sleep(3)
rednet.broadcast("cause I rule my world")
sleep(3)
rednet.broadcast("Made in 3 by 3")
sleep(3)
rednet.broadcast("Im-a blow stuff up")
sleep(3)
rednet.broadcast("With my TNT")
sleep(3)
rednet.broadcast("Im gonna blow it all up")
sleep(3)
rednet.broadcast("Every mountain every valley")
sleep(3)
rednet.broadcast("Ruler of the world, yep")
sleep(3)
rednet.broadcast("All of the animals will fear me")
sleep(3)
rednet.broadcast("cause TNT is awesome")
sleep(3)
rednet.broadcast("And TNT, is just really cool, is just really cool")
sleep(3)
rednet.broadcast("Im gonna shoot my arrows in the air")
sleep(3)
rednet.broadcast("Arrows in the the air")
sleep(3)
rednet.broadcast("Shoot your arrows in the aaaiiirrr...")
sleep(3)
rednet.broadcast("I shoot my arrows in the air sometimes")
sleep(3)
rednet.broadcast("Sayin ay-oh, Creepers K-Od")
sleep(3)
rednet.broadcast("TeaBag his ghost and now his sulphurs mine")
sleep(3)
rednet.broadcast("Saying ay-oh, MLG pro")
sleep(3)
rednet.broadcast("And then Ill head back home")
sleep(3)
rednet.broadcast("Where Ill smile with glee")
sleep(3)
rednet.broadcast("Now that I can make")
sleep(3)
rednet.broadcast("tons of TNT")
sleep(3)
rednet.broadcast("cause I rule my world")
sleep(3)
rednet.broadcast("Made in 3 by 3")
sleep(3)
rednet.broadcast("Im-a blow stuff up")
sleep(3)
rednet.broadcast("With my TNT ")
sleep(3)
rednet.broadcast("Next song planned in 5 minutes.")
print("Tnt radio done, Cube land.")
print("5 min")
sleep(60)
print("4 min")
sleep(60)
print("3 min")
sleep(30)
print("30 sec AD")
rednet.broadcast("If you want the radio to")
sleep(5)
rednet.broadcast("broadcast a song you want")
sleep(5)
rednet.broadcast("or have an ad on it,")
sleep(5)
rednet.broadcast("ask Russian_spy to")
sleep(5)
rednet.broadcast("add your ad or song")
sleep(5)
rednet.broadcast("to the radio.(Currently free)")
sleep(5)
print("2 min")
sleep(60)
print("1 min")
sleep(60)










print("Cube Land started...")
rednet.broadcast("Statilite radio, broadcasting here:")
sleep(3)
rednet.broadcast("Cube land by: Laura Shigihara")
sleep(3)
rednet.broadcast("Im in a cube land")
sleep(3)
rednet.broadcast("I dig with cold hands")
sleep(3)
rednet.broadcast("I use these tools to try and")
sleep(3)
rednet.broadcast("Climb out of this mess Ive made")
sleep(3)
rednet.broadcast("My door is open")
sleep(3)
rednet.broadcast("Skeletons and zombies")
sleep(3)
rednet.broadcast("I am broken, as they walk all over me")
sleep(3)
rednet.broadcast("But if I keep on building walls,")
sleep(3)
rednet.broadcast("Maybe theyll stay away")
sleep(3)
rednet.broadcast("Think fast, its got to last if youre")
sleep(3)
rednet.broadcast("Gonna make it through the rest of the day")
sleep(3)
rednet.broadcast("Im trapped, I cant go back, Ive made the choice to stay")
sleep(3)
rednet.broadcast("And well fight... keep defending through the night")
sleep(3)
rednet.broadcast("well fight the good fight")
sleep(3)
rednet.broadcast("Live... were all driven to survive")
sleep(3)
rednet.broadcast("well fight the good fight")
sleep(3)
rednet.broadcast("Ill keep going, just stay by my side.")
sleep(3)
rednet.broadcast("Im in a cube land")
sleep(3)
rednet.broadcast("My castles so grand")
sleep(3)
rednet.broadcast("And once I lay these tracks Ill finally make my escape")
sleep(3)
rednet.broadcast("I am no one")
sleep(3)
rednet.broadcast("I have no place, no one relates")
sleep(3)
rednet.broadcast("And there is no sun")
sleep(3)
rednet.broadcast("As the night covers this space")
sleep(3)
rednet.broadcast("But I beg you, please please dont let this life go to waste")
sleep(3)
rednet.broadcast("Think fast, its got to last if youre")
sleep(3)
rednet.broadcast("Gonna make it through the rest of the day")
sleep(3)
rednet.broadcast("Im trapped, I cant go back, Ive made the choice to stay")
sleep(3)
rednet.broadcast("And well fight... keep defending through the night")
sleep(3)
rednet.broadcast("well fight the good fight")
sleep(3)
rednet.broadcast("Live... were all driven to survive")
sleep(3)
rednet.broadcast("well fight the good fight")
sleep(3)
rednet.broadcast("Ill keep going, just stay by my side.")
sleep(3)
rednet.broadcast("Next song planned in 5 minutes.")
print("Cube land done, Nyan cat is next XD.")
print("5 min")
sleep(60)
print("4 min")
sleep(60)
print("3 min")
sleep(60)
print("2 min")
sleep(60)
print("1 min")
sleep(60)






print("Nyan cat started XD...")

nyan = 0

rednet.broadcast("Statilite radio, broadcasting here:")
sleep(1)
rednet.broadcast("NYAN CAT XD!!! Requested by: [Admin]Dusty")
sleep(3)
while nyan <10 do rednet.broadcast("Nyan nyan nyan") sleep(3)  nyan = nyan + 1 end
rednet.broadcast("Next song planned in 5 minutes.")
print("Nyan cat done, Revenge is next.")
print("5 min")
sleep(60)
print("4 min")
sleep(60)
print("3 min")
sleep(60)
print("2 min")
sleep(60)
print("1 min")
sleep(60)









print("Revenge started...")

rednet.broadcast("Statilite radio, broadcasting here:")
sleep(3)
rednet.broadcast("Revenge by Captn Sparkles.")
sleep(3)
rednet.broadcast("So we back in the mine, got our")
sleep(3)
rednet.broadcast("pick axe swinging from side to side,")
sleep(3)
rednet.broadcast("This task a grueling one, hope")
sleep(3)
rednet.broadcast("to find some diamonds tonight,")
sleep(3)
rednet.broadcast("Heads up, you hear a sound, turn")
sleep(3)
rednet.broadcast("around and look up, total shock fills your body,")
sleep(3)
rednet.broadcast("Oh no its you again,")
sleep(3)
rednet.broadcast("I could never forget those eyes")
sleep(3)
rednet.broadcast("Cause baby tonight, the creepers")
sleep(3)
rednet.broadcast("trying to steal all our stuff again,")
sleep(3)
rednet.broadcast("Cause baby tonight, you grab your")
sleep(3)
rednet.broadcast("pick, shovel and bolt again,")
sleep(3)
rednet.broadcast("And run, run until its done, done,")
sleep(3)
rednet.broadcast("until the sun comes up in the morn")
sleep(3)
rednet.broadcast("Cause baby tonight, the creepers")
sleep(3)
rednet.broadcast("trying to steal all our stuff again,")
sleep(3)
rednet.broadcast("Just when you think youre safe,")
sleep(3)
rednet.broadcast("overhear some hissing from right behind,")
sleep(3)
rednet.broadcast("Thats a nice life you have, shame")
sleep(3)
rednet.broadcast("its gotta end at this time,")
sleep(3)
rednet.broadcast("Blows up, then your health bar drops,")
sleep(3)
rednet.broadcast("you could use a 1-up, get inside dont be tardy,")
sleep(3)
rednet.broadcast("So now youre stuck in there, half")
sleep(3)
rednet.broadcast("a heart is left but dont die")
sleep(3)
rednet.broadcast("Cause baby tonight, the creepers")
sleep(3)
rednet.broadcast("trying to steal all your stuff again,")
sleep(3)
rednet.broadcast("Cause baby tonight, you grab your")
sleep(3)
rednet.broadcast("pick, shovel and bolt again,")
sleep(3)
rednet.broadcast("And run, run until its done, done,")
sleep(3)
rednet.broadcast("until the sun comes up in the morn")
sleep(3)
rednet.broadcast("Cause baby tonight, the creepers")
sleep(3)
rednet.broadcast("trying to steal all your stuff again,")
sleep(3)
rednet.broadcast("Creepers, youre mine")
sleep(3)
rednet.broadcast("Dig up diamonds, and craft")
sleep(3)
rednet.broadcast("those diamonds and make some armor,")
sleep(3)
rednet.broadcast("Get it baby, go and forge")
sleep(3)
rednet.broadcast("that like you so, MLG pro,")
sleep(3)
rednet.broadcast("The swords made of diamonds,")
sleep(3)
rednet.broadcast("so come at me bro")
sleep(3)
rednet.broadcast("Training in your room under")
sleep(3)
rednet.broadcast("the torch light,")
sleep(3)
rednet.broadcast("Hone that form to get you ready")
sleep(3)
rednet.broadcast("for the big fight,")
sleep(3)
rednet.broadcast("Every single day and the whole night,")
sleep(3)
rednet.broadcast("Creepers out prowlin - alright")
sleep(3)
rednet.broadcast("Look at me, look at you,")
sleep(3)
rednet.broadcast("Take my revenge thats what Im gonna do,")
sleep(3)
rednet.broadcast("Im a warrior baby, what else is new,")
sleep(3)
rednet.broadcast("And my blades gonna tear through you")
sleep(3)
rednet.broadcast("Cause baby tonight, the creepers")
sleep(3)
rednet.broadcast("trying to steal all our stuff again,")
sleep(3)
rednet.broadcast("Yeah baby tonight, grab your sword,")
sleep(3)
rednet.broadcast("armor and go, take your revenge,")
sleep(3)
rednet.broadcast("So fight, fight like its the last,")
sleep(3)
rednet.broadcast("last night of your life, life, show them your bite,")
sleep(3)
rednet.broadcast("Cause baby tonight, the creepers")
sleep(3)
rednet.broadcast("trying to steal all our stuff again,")
sleep(3)
rednet.broadcast("Cause baby tonight, you grab your")
sleep(3)
rednet.broadcast("pick, shovel and bolt again,")
sleep(3)
rednet.broadcast("And run, run until its done, done,")
sleep(3)
rednet.broadcast("until the sun comes up in the morn")
sleep(3)
rednet.broadcast("Cause baby tonight, the creepers")
sleep(3)
rednet.broadcast("tried to steal all our stuff again.")
sleep(3)
rednet.broadcast("Next song planned in 5 minutes.")
print("Revenge done, Glowstone love is next")
print("5 min")
sleep(60)
print("4 min")
sleep(60)
print("3 min")
sleep(60)
print("2 min")
sleep(60)
print("1 min")
sleep(60)







print("Glowstone love started")
rednet.broadcast("Statilite radio, broadcasting here:")
sleep(3)
rednet.broadcast("Glowsotone love by ItsAllMinecraft.")
sleep(3)
rednet.broadcast("You give me light,")
sleep(3)
rednet.broadcast("when Im in a cave")
sleep(3)
rednet.broadcast("You make it bright,")
sleep(3)
rednet.broadcast("So I can be brave.")
sleep(3)
rednet.broadcast("And Ill travel to")
sleep(3)
rednet.broadcast("the underground")
sleep(3)
rednet.broadcast("Just to bring you")
sleep(3)
rednet.broadcast("back, safe and sound with me")
sleep(3)
rednet.broadcast("I had to break you")
sleep(3)
rednet.broadcast("but Ill put you back together")
sleep(3)
rednet.broadcast("Forever together")
sleep(3)
rednet.broadcast("Just think of all")
sleep(3)
rednet.broadcast("the times well have")
sleep(3)
rednet.broadcast("Illuminate my dark")
sleep(3)
rednet.broadcast("and boring past")
sleep(3)
rednet.broadcast("I knew I couldnt")
sleep(3)
rednet.broadcast("do this on my own")
sleep(3)
rednet.broadcast("I love you, cause")
sleep(3)
rednet.broadcast("youre my Glowstone.")
sleep(3)
rednet.broadcast("Ill risk my life,")
sleep(3)
rednet.broadcast("going to the nether")
sleep(3)
rednet.broadcast("And Ill be fine,")
sleep(3)
rednet.broadcast("but with you Ill be better.")
sleep(3)
rednet.broadcast("And that golden look")
sleep(3)
rednet.broadcast("just makes me smile")
sleep(3)
rednet.broadcast("And you light up the")
sleep(3)
rednet.broadcast("night think Ill stay for a while")
sleep(3)
rednet.broadcast("Who knows.")
sleep(3)
rednet.broadcast("Dont tell but I think I")
sleep(3)
rednet.broadcast("like you better")
sleep(3)
rednet.broadcast("than my diamond clothes.")
sleep(3)
rednet.broadcast("Now its bright in")
sleep(3)
rednet.broadcast("the mine at last")
sleep(3)
rednet.broadcast("The expectations that")
sleep(3)
rednet.broadcast("Ive had for you, youve past")
sleep(3)
rednet.broadcast("The attachment that I")
sleep(3)
rednet.broadcast("have I wouldve never known")
sleep(3)
rednet.broadcast("I LOVE YOU")
sleep(3)
rednet.broadcast("CUASE YOURE MY #GLOWSTONE")
sleep(3)
rednet.broadcast("Glow, stone")
sleep(3)
rednet.broadcast("Cuase youre my Glowstone")
sleep(3)
rednet.broadcast("Glow, stone")
sleep(3)
rednet.broadcast("And I wish it was forever")
sleep(3)
rednet.broadcast("the time that were together")
sleep(3)
rednet.broadcast("I hop you never grow")
sleep(3)
rednet.broadcast("old and youll never grow dim")
sleep(3)
rednet.broadcast("That youre the same")
sleep(3)
rednet.broadcast("light that youve always been")
sleep(3)
rednet.broadcast("Because its you and")
sleep(3)
rednet.broadcast("me I light up at the thought")
sleep(3)
rednet.broadcast("Miners are scared of")
sleep(3)
rednet.broadcast("the dark. But with you Im not.")
sleep(3)
rednet.broadcast("And can we keep this")
sleep(3)
rednet.broadcast("the same. Everyday is a clone.")
sleep(3)
rednet.broadcast("I love you, cause youre")
sleep(3)
rednet.broadcast("my glowstoooooooooooooooone")
sleep(3)
rednet.broadcast("Youre, youre my glowstone,")
sleep(3)
rednet.broadcast("youre, youre my glowstone.")
sleep(3)
rednet.broadcast("Next song planned in 5 minutes.")
print("Glowstone love is done, Enderborn is next")
print("5 min")
sleep(60)
print("4 min")
sleep(60)
print("3 min")
sleep(60)
print("2 min")
sleep(60)
print("1 min")
sleep(60)






print("Enderborn started")
rednet.broadcast("Statilite radio, broadcasting here:")
sleep(3)
rednet.broadcast("Enderborn by BlahBlahBlahGAMING.")
sleep(3)
rednet.broadcast("Steve was his name")
sleep(3)
rednet.broadcast("just a man from block land")
sleep(3)
rednet.broadcast("he just dug, what he could")
sleep(3)
rednet.broadcast("and hit wood with his hand")
sleep(3)
rednet.broadcast("but he soon found out that he was much,")
sleep(3)
rednet.broadcast("much much more than a man")
sleep(3)
rednet.broadcast("When he found a small cave")
sleep(3)
rednet.broadcast("there was a strange tall man")
sleep(3)
rednet.broadcast("he told Steve that he was")
sleep(3)
rednet.broadcast("Enderborn, he must save")
sleep(3)
rednet.broadcast("the world from the greatest")
sleep(3)
rednet.broadcast("threat it has ever seen,")
sleep(3)
rednet.broadcast("Now you must go to slay the Enderman")
sleep(3)
rednet.broadcast("to collect ender pearls to")
sleep(3)
rednet.broadcast("fulfill the plan")
sleep(3)
rednet.broadcast("destined to save the world")
sleep(3)
rednet.broadcast("from an ender dragon")
sleep(3)
rednet.broadcast("and well see, on this day,")
sleep(3)
rednet.broadcast("that a legend began")
sleep(3)
rednet.broadcast("Steve now he knew")
sleep(3)
rednet.broadcast("that he was Enderborn")
sleep(3)
rednet.broadcast("ventured home made a sword,")
sleep(3)
rednet.broadcast("and then left before dawn,")
sleep(3)
rednet.broadcast("and he slayed Endermen")
sleep(3)
rednet.broadcast("until he had enough...")
sleep(3)
rednet.broadcast("He searched far he searched wide")
sleep(3)
rednet.broadcast("until he found the Stronghold")
sleep(3)
rednet.broadcast("so he could find the end")
sleep(3)
rednet.broadcast("and do whats foretold")
sleep(3)
rednet.broadcast("used the pearls that he")
sleep(3)
rednet.broadcast("gained to open the door")
sleep(3)
rednet.broadcast("to the end, save a world,")
sleep(3)
rednet.broadcast("that he cares so much for")
sleep(3)
rednet.broadcast("Right through the door")
sleep(3)
rednet.broadcast("was a world, filled with black")
sleep(3)
rednet.broadcast("Endermen, they stood guard and")
sleep(3)
rednet.broadcast("but he climbed the black towers and")
sleep(3)
rednet.broadcast("smashed the crystals")
sleep(3)
rednet.broadcast("Dragon flies, dragon turns, then")
sleep(3)
rednet.broadcast("swoops down for Steve,")
sleep(3)
rednet.broadcast("standing calm, cause he knows,")
sleep(3)
rednet.broadcast("he has a trick up his sleeve")
sleep(3)
rednet.broadcast("swings his sword, like a Nord,")
sleep(3)
rednet.broadcast("on the dragons big snout")
sleep(3)
rednet.broadcast("dragon turns, flies away,")
sleep(3)
rednet.broadcast("with a roaring loud shout")
sleep(3)
rednet.broadcast("Dragon flies, dragon turns,")
sleep(3)
rednet.broadcast("swoops for one last fight")
sleep(3)
rednet.broadcast("grabs his bow, cause hes pro,")
sleep(3)
rednet.broadcast("Steve hits him mid flight")
sleep(3)
rednet.broadcast("dragon dies, dragon fades,")
sleep(3)
rednet.broadcast("said he glew like the sun")
sleep(3)
rednet.broadcast("so its said, on this day,")
sleep(3)
rednet.broadcast("that a legend began.")
sleep(3)
rednet.broadcast("Next song planned in 5 minutes.")
print("Enderborn is done, Still alive is next")
print("5 min")
sleep(60)
print("4 min")
sleep(60)
print("3 min")
sleep(60)
print("2 min")
sleep(60)
print("1 min")
sleep(60)



end
